EXERIMENT 11

CATEGORICAL DATA ANALYSIS USING PYTHON.

ROHAN KUMBHAR

PRN:- 25070123141

In [1]:
import pandas as pd
data = {
    'Order_ID':['01','02','03','04','05','06','07','08','09','010'],
    'Category':['Eletonics','Clothing','Eletonics','Grocery','Clothing','Eleronics','Grocery','Clothing','Electronics','Grocery'],
    'Payemnt_Method':['UPI','Card','UPI','Cash','Card','UPI','Cash','Card','UPI','Cash'],
    'Delivery_Type':['Express','Standard','Express','Standard','Express','Standard','Express','Standard','Express','Standard'],
    'Customer_Type:':['New','Returning','Returning','New','Returning','New','Returning','New','Returning','New']


}
df=pd.DataFrame(data)
print(df)

  Order_ID     Category Payemnt_Method Delivery_Type Customer_Type:
0       01    Eletonics            UPI       Express            New
1       02     Clothing           Card      Standard      Returning
2       03    Eletonics            UPI       Express      Returning
3       04      Grocery           Cash      Standard            New
4       05     Clothing           Card       Express      Returning
5       06    Eleronics            UPI      Standard            New
6       07      Grocery           Cash       Express      Returning
7       08     Clothing           Card      Standard            New
8       09  Electronics            UPI       Express      Returning
9      010      Grocery           Cash      Standard            New

In [2]:
#1. Frequency Count
#Count how many orders in each category

print(df['Category'].value_counts())

Category
Clothing       3
Grocery        3
Eletonics      2
Eleronics      1
Electronics    1
Name: count, dtype: int64

In [3]:
#3. Number of Unique Values
print(df['Category'].nunique())

5

In [4]:
#4. Frequecy of Payment Methods
print(df['Payemnt_Method'].value_counts())

Payemnt_Method
UPI     4
Card    3
Cash    3
Name: count, dtype: int64

In [5]:
#5. cross Tabulation
#category vs Payment Method

print(pd.crosstab(df['Category'],df['Payemnt_Method']))

Payemnt_Method  Card  Cash  UPI
Category
Clothing           3     0    0
Electronics        0     0    1
Eleronics          0     0    1
Eletonics          0     0    2
Grocery            0     3    0

In [7]:
#6. Cross Tabulation (Delivery vs Customer Type)
print(pd.crosstab(df['Delivery_Type'],df['Customer_Type:']))

Customer_Type:  New  Returning
Delivery_Type
Express           1          4
Standard          4          1

In [8]:
#7. Percentage Distribution
print(df['Category'].value_counts(normalize=True)*100)

Category
Clothing       30.0
Grocery        30.0
Eletonics      20.0
Eleronics      10.0
Electronics    10.0
Name: proportion, dtype: float64

In [9]:
#8.Filtering Data
#Example:Orders from Eletronics category
electronics_orders=df[df['Category']=='Eletonics']
print(electronics_orders)

  Order_ID   Category Payemnt_Method Delivery_Type Customer_Type:
0       01  Eletonics            UPI       Express            New
2       03  Eletonics            UPI       Express      Returning

In [10]:
#8.Filtering Data
#Example:Orders from Eletronics category
electronics_orders=df[df['Category']=='Clothing']
print(electronics_orders)

  Order_ID  Category Payemnt_Method Delivery_Type Customer_Type:
1       02  Clothing           Card      Standard      Returning
4       05  Clothing           Card       Express      Returning
7       08  Clothing           Card      Standard            New

In [11]:
#9.Grouping
#Orders by category and payment method
print(df.groupby(['Category','Payemnt_Method']).value_counts())

Category     Payemnt_Method  Order_ID  Delivery_Type  Customer_Type:
Clothing     Card            02        Standard       Returning         1
                             05        Express        Returning         1
                             08        Standard       New               1
Electronics  UPI             09        Express        Returning         1
Eleronics    UPI             06        Standard       New               1
Eletonics    UPI             01        Express        New               1
                             03        Express        Returning         1
Grocery      Cash            010       Standard       New               1
                             04        Standard       New               1
                             07        Express        Returning         1
Name: count, dtype: int64

In [14]:
#SECOND DATASET
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Expt11.csv')
df

   Student  Gender  Department Grade
0       S1    Male         CSE     A
1       S2  Female          IT     B
2       S3  Female         CSE     A
3       S4    Male         ECE     C
4       S5    Male          IT     B
5       S6  Female         CSE     A
6       S7    Male  Mechanical     B
7       S8  Female          IT     A
8       S9    Male         CSE     C
9      S10  Female         ECE     B
10     S11    Male         CSE     A
11     S12  Female          IT     B
12     S13    Male  Mechanical     C
13     S14  Female         CSE     A
14     S15    Male          IT     B
15     S16  Female         ECE     A
16     S17    Male         CSE     B
17     S18  Female          IT     C
18     S19    Male  Mechanical     B
19     S20  Female         CSE     A
20     S21    Male         ECE     C
21     S22  Female          IT     B
22     S23    Male         CSE     A
23     S24  Female  Mechanical     B
24     S25    Male          IT     A
25     S26  Female         CSE     C
26     S27    Male         ECE     B
27     S28  Female          IT     A
28     S29    Male  Mechanical     C
29     S30  Female         CSE     B
30     S31    Male          IT     A
31     S32  Female         ECE     B
32     S33    Male         CSE     A
33     S34  Female  Mechanical     C
34     S35    Male          IT     B
35     S36  Female         CSE     A
36     S37    Male         ECE     B
37     S38  Female          IT     C
38     S39    Male  Mechanical     B
39     S40  Female         CSE     A
40     S41    Male          IT     B
41     S42  Female         ECE     A
42     S43    Male         CSE     C
43     S44  Female  Mechanical     B
44     S45    Male          IT     A
45     S46  Female         CSE     B
46     S47    Male         ECE     C
47     S48  Female          IT     A
48     S49    Male  Mechanical     B
49     S50  Female         CSE     A
50     S51    Male          IT     B
51     S52  Female         ECE     C
52     S53    Male         CSE     A
53     S54  Female  Mechanical     B
54     S55    Male          IT     C
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [15]:
df.head()

  Student  Gender Department Grade
0      S1    Male        CSE     A
1      S2  Female         IT     B
2      S3  Female        CSE     A
3      S4    Male        ECE     C
4      S5    Male         IT     B

In [16]:
df.tail()

   Student  Gender  Department Grade
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [17]:
#1.Count Students obtained Each grade
print(df['Grade'].value_counts())

Grade
B    24
A    22
C    14
Name: count, dtype: int64

In [18]:
#2.Percentage distribution of grades
print(df['Grade'].value_counts(normalize=True)*100)

Grade
B    40.000000
A    36.666667
C    23.333333
Name: proportion, dtype: float64

In [19]:
#3.Number of Students in each department
print(df['Department'].value_counts())

Department
CSE           20
IT            18
ECE           11
Mechanical    11
Name: count, dtype: int64

In [20]:
#4.Gender distribution
print(df['Gender'].value_counts())

Gender
Male      30
Female    30
Name: count, dtype: int64

In [21]:
#5.Gender VS grade analysis
print(pd.crosstab(df['Gender'],df['Grade']))

Grade    A   B  C
Gender
Female  14  11  5
Male     8  13  9

In [22]:
#6. Department vs Gender analysis
print(pd.crosstab(df['Department'],df['Gender']))

Gender      Female  Male
Department
CSE             12     8
ECE              5     6
IT               9     9
Mechanical       4     7

In [23]:
#7.Department vs grade pecentage
print(pd.crosstab(df['Department'],df['Grade'],normalize='index')*100)

Grade               A          B          C
Department
CSE         65.000000  20.000000  15.000000
ECE         18.181818  45.454545  36.363636
IT          38.888889  44.444444  16.666667
Mechanical   0.000000  63.636364  36.363636

In [26]:
#8. Grouping Data(Departmentwise)
print(df.groupby('Department')['Grade'].value_counts())

Department  Grade
CSE         A        13
            B         4
            C         3
ECE         B         5
            C         4
            A         2
IT          B         8
            A         7
            C         3
Mechanical  B         7
            C         4
Name: count, dtype: int64